#!/bin/sh
# .husky/pre-push

. "$(dirname "$0")/_/husky.sh"

# Detected changes in the src directory, running checks...
if git diff --name-only @{u}..HEAD | grep -Eq '^(src)/'; then
  echo "Detected changes, building..."
  npm run build
fi